services:
  - type: web
    name: underwritepro-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && python main_apple_grade.py"
    envVars:
      - key: JWT_SECRET_KEY
        value: e7d0ef4a67518c6ce9849a5f133033df1bcd3110bb4accfecf2dc5516b13f9a0
      - key: OPENAI_API_KEY
        value: sk-gU2FSLRqSNMJsvWm7ewuDX
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
