services:
  # PostgreSQL Database
  - type: pserv
    name: underwritepro-db
    env: docker
    plan: standard  # Render Pro plan
    region: oregon
    databaseName: underwritepro
    databaseUser: underwritepro
    ipAllowList: []

  # Web Service (Backend + Frontend)
  - type: web
    name: underwritepro
    env: python
    plan: standard  # Render Pro plan
    region: oregon
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn main_production:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: underwritepro-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false  # Will be set manually
