services:
  - type: web
    name: underwritepro-saas
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main_production:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: underwritepro-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: underwritepro-db
    databaseName: underwritepro
    user: underwritepro
